//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Client.Games.Fallout4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Client.Games.Fallout4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;categoryManager fileVersion=&quot;0.1.0.0&quot;&gt;
        ///  &lt;categoryList&gt;
        ///    &lt;category path=&quot;Ammo&quot; ID=&quot;3&quot;&gt;
        ///      &lt;name&gt;Ammo&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Animation&quot; ID=&quot;4&quot;&gt;
        ///      &lt;name&gt;Animation&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Armour&quot; ID=&quot;5&quot;&gt;
        ///      &lt;name&gt;Armour&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Audio - Misc&quot; ID=&quot;35&quot;&gt;
        ///      &lt;name&gt;Audio - Misc&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Audio - Music&quot; ID=&quot;34&quot;&gt;
        ///      &lt;name&gt;Audio - Music&lt;/na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallout4 - Animations.ba2
        ///Fallout4 - Geometry.csg
        ///Fallout4 - Interface.ba2
        ///Fallout4 - Materials.ba2
        ///Fallout4 - Meshes.ba2
        ///Fallout4 - MeshesExtra.ba2
        ///Fallout4 - Misc.ba2
        ///Fallout4 - Nvflex.ba2
        ///Fallout4 - Shaders.ba2
        ///Fallout4 - Sounds.ba2
        ///Fallout4 - Startup.ba2
        ///Fallout4 - Textures1.ba2
        ///Fallout4 - Textures2.ba2
        ///Fallout4 - Textures3.ba2
        ///Fallout4 - Textures4.ba2
        ///Fallout4 - Textures5.ba2
        ///Fallout4 - Textures6.ba2
        ///Fallout4 - Textures7.ba2
        ///Fallout4 - Textures8.ba2
        ///Fallout4 - Textures9.ba2
        ///Fallout4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fallout4_base {
            get {
                return ResourceManager.GetString("fallout4_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Fallout4_logo {
            get {
                object obj = ResourceManager.GetObject("Fallout4_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
