//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Client.Games.SkyrimSE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Client.Games.SkyrimSE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;categoryManager fileVersion=&quot;0.1.0.0&quot;&gt;
        ///  &lt;categoryList&gt;
        ///    &lt;category path=&quot;Unassigned&quot; ID=&quot;0&quot;&gt;
        ///      &lt;name&gt;Unassigned&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Player homes&quot; ID=&quot;67&quot;&gt;
        ///      &lt;name&gt;Player homes&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Creatures&quot; ID=&quot;83&quot;&gt;
        ///      &lt;name&gt;Creatures&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Animation&quot; ID=&quot;51&quot;&gt;
        ///      &lt;name&gt;Animation&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Armour&quot; ID=&quot;54&quot;&gt;
        ///      &lt;name&gt;Armo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawnguard.esm
        ///Dragonborn.esm
        ///HearthFires.esm
        ///Skyrim - Animations.bsa
        ///Skyrim - Interface.bsa
        ///Skyrim - Meshes0.bsa
        ///Skyrim - Meshes1.bsa
        ///Skyrim - Misc.bsa
        ///Skyrim - Patch.bsa
        ///Skyrim - Shaders.bsa
        ///Skyrim - Sounds.bsa
        ///Skyrim - Textures0.bsa
        ///Skyrim - Textures1.bsa
        ///Skyrim - Textures2.bsa
        ///Skyrim - Textures3.bsa
        ///Skyrim - Textures4.bsa
        ///Skyrim - Textures5.bsa
        ///Skyrim - Textures6.bsa
        ///Skyrim - Textures7.bsa
        ///Skyrim - Textures8.bsa
        ///Skyrim - Voices_en0.bsa
        ///Skyrim.esm
        ///Update.esm
        ///Video\BGS_Logo.bik.
        /// </summary>
        public static string SkyrimSE_base {
            get {
                return ResourceManager.GetString("SkyrimSE_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon SkyrimSE_logo {
            get {
                object obj = ResourceManager.GetObject("SkyrimSE_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
