//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Client.Games.Skyrim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Client.Games.Skyrim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;categoryManager fileVersion=&quot;0.1.0.0&quot;&gt;
        ///  &lt;categoryList&gt;
        ///    &lt;category path=&quot;Abodes - Player homes&quot; ID=&quot;67&quot;&gt;
        ///      &lt;name&gt;Abodes - Player homes&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Animals, creatures, mounts &amp;amp; horses&quot; ID=&quot;83&quot;&gt;
        ///      &lt;name&gt;Animals, creatures, mounts &amp;amp; horses&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Animation&quot; ID=&quot;51&quot;&gt;
        ///      &lt;name&gt;Animation&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Armour&quot; ID=&quot;54&quot;&gt;
        ///      &lt;name&gt;Armour&lt;/name&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawnguard.bsa
        ///Dawnguard.esm
        ///Dragonborn.bsa
        ///Dragonborn.esm
        ///HearthFires.bsa
        ///HearthFires.esm
        ///HighResTexturePack01.bsa
        ///HighResTexturePack01.esp
        ///HighResTexturePack02.bsa
        ///HighResTexturePack02.esp
        ///HighResTexturePack03.bsa
        ///HighResTexturePack03.esp
        ///Interface\Translate_English.txt
        ///Skyrim - Animations.bsa
        ///Skyrim - Interface.bsa
        ///Skyrim - Meshes.bsa
        ///Skyrim - Misc.bsa
        ///Skyrim - Shaders.bsa
        ///Skyrim - Sounds.bsa
        ///Skyrim - Textures.bsa
        ///Skyrim - Voices.bsa
        ///Skyrim.esm
        ///Strings\Skyrim_English.DLStrings
        ///Strin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string skyrim_base {
            get {
                return ResourceManager.GetString("skyrim_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon skyrim_logo {
            get {
                object obj = ResourceManager.GetObject("skyrim_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
