//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Client.Games.EnderalSE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Client.Games.EnderalSE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;categoryManager fileVersion=&quot;0.1.0.0&quot;&gt;
        ///  &lt;categoryList&gt;
        ///    &lt;category path=&quot;Animations&quot; ID=&quot;18&quot;&gt;
        ///      &lt;name&gt;Animations&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Apparel&quot; ID=&quot;7&quot;&gt;
        ///      &lt;name&gt;Apparel&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Audio&quot; ID=&quot;4&quot;&gt;
        ///      &lt;name&gt;Audio&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Characters&quot; ID=&quot;12&quot;&gt;
        ///      &lt;name&gt;Characters&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Creatures&quot; ID=&quot;9&quot;&gt;
        ///      &lt;name&gt;Creatures&lt;/name&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface\Translate_English.txt
        ///E - Meshes.bsa
        ///E - Music.bsa
        ///E - Scripts.bsa
        ///E - Sounds.bsa
        ///E - Textures1.bsa
        ///E - Textures2.bsa
        ///E - Textures3.bsa
        ///Enderal - Forgotten Stories.esm
        ///L - Textures.bsa
        ///L - Voices.bsa
        ///Skyrim - Animations.bsa
        ///Skyrim - Interface.bsa
        ///Skyrim - Meshes.bsa
        ///Skyrim - Misc.bsa
        ///Skyrim - Shaders.bsa
        ///Skyrim - Sounds.bsa
        ///Skyrim - Textures.bsa
        ///Skyrim.esm
        ///Update.bsa
        ///Update.esm
        ///Video\Enderal_Credits.bik
        ///Video\EnderalIntro.bik
        ///Video\MQ17BlackGuardian.bik
        ///Video\MQP03NearDeath [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnderalSE_base {
            get {
                return ResourceManager.GetString("EnderalSE_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon EnderalSE_logo {
            get {
                object obj = ResourceManager.GetObject("EnderalSE_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
