<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Target Name="CleanMirroredScriptTypes" AfterTargets="Build">
		<ItemGroup>
			<MirroredScriptTypes Include="$(SolutionDir)\Stage\$(Configuration)\GameModes\Antlr3.Runtime.dll" />
			<MirroredScriptTypes Include="$(SolutionDir)\Stage\$(Configuration)\GameModes\AntlrUtil.dll" />
			<MirroredScriptTypes Include="$(SolutionDir)\Stage\$(Configuration)\GameModes\CSharpScript.dll" />
			<MirroredScriptTypes Include="$(SolutionDir)\Stage\$(Configuration)\GameModes\ModScript.dll" />
			<MirroredScriptTypes Include="$(SolutionDir)\Stage\$(Configuration)\GameModes\XmlScript.dll" />
		</ItemGroup>

		<Message Text="Removing legacy mirrored ScriptType files from GameModes..." Importance="High" />
		<Delete Files="@(MirroredScriptTypes)" />
	</Target>
</Project>
