using System;
using System.Collections.Generic;
using Nexus.Client.Mods;

namespace Nexus.Client.Games
{
	/// <summary>
	/// Exposes a side-effect-free exact generated-file plan for legacy game modes whose BasicInstall path merges one archive file.
	/// </summary>
	public interface IDeterministicModFileMergePlanProvider
	{
		/// <summary>
		/// Builds the exact generated replacement for the current mod without writing native state, or returns <c>null</c> when
		/// the current archive does not contribute to the game-specific merged file.
		/// </summary>
		DeterministicModFileMergePlan GetDeterministicModFileMergePlan(IList<IMod> activeMods, IMod currentMod);
	}

	/// <summary>
	/// Describes one exact generated output replacing a legacy merged archive source during deterministic BasicInstall planning.
	/// </summary>
	public sealed class DeterministicModFileMergePlan
	{
		/// <summary>Creates one immutable deterministic merge result.</summary>
		public DeterministicModFileMergePlan(string sourcePath, string destinationPath, byte[] data)
		{
			if (String.IsNullOrWhiteSpace(sourcePath))
				throw new ArgumentException("A deterministic merge plan requires the contributing archive source path.", nameof(sourcePath));
			if (String.IsNullOrWhiteSpace(destinationPath))
				throw new ArgumentException("A deterministic merge plan requires a generated destination path.", nameof(destinationPath));
			if (data == null || data.Length == 0)
				throw new ArgumentException("A deterministic merge plan requires non-empty generated bytes.", nameof(data));

			SourcePath = sourcePath;
			DestinationPath = destinationPath;
			Data = (byte[])data.Clone();
		}

		/// <summary>Gets the archive source path replaced by the merged generated output.</summary>
		public string SourcePath { get; }

		/// <summary>Gets the logical generated destination relative to the normal Data deployment root.</summary>
		public string DestinationPath { get; }

		/// <summary>Gets a defensive copy of the generated bytes.</summary>
		public byte[] Data { get; }
	}
}
