//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Client.Games.FalloutNV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Client.Games.FalloutNV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;categoryManager fileVersion=&quot;0.1.0.0&quot;&gt;
        ///  &lt;categoryList&gt;
        ///    &lt;category path=&quot;Default&quot; ID=&quot;99&quot;&gt;
        ///      &lt;name&gt;Default&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Animation&quot; ID=&quot;56&quot;&gt;
        ///      &lt;name&gt;Animation&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Armor&quot; ID=&quot;69&quot;&gt;
        ///      &lt;name&gt;Armor&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Bug Fixes&quot; ID=&quot;100&quot;&gt;
        ///      &lt;name&gt;Bug Fixes&lt;/name&gt;
        ///    &lt;/category&gt;
        ///    &lt;category path=&quot;Buildings&quot; ID=&quot;72&quot;&gt;
        ///      &lt;name&gt;Buildings&lt;/name&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaravanPack - Main.bsa
        ///CaravanPack.esm
        ///CARAVANPACK.NAM
        ///ClassicPack - Main.bsa
        ///ClassicPack.esm
        ///CLASSICPACK.NAM
        ///credits.txt
        ///CreditsWacky.txt
        ///DeadMoney - Main.bsa
        ///DeadMoney - Sounds.bsa
        ///DeadMoney.esm
        ///DEADMONEY.NAM
        ///Fallout - AI!.bsa
        ///Fallout - Meshes.bsa
        ///Fallout - Misc.bsa
        ///Fallout - Sound.bsa
        ///Fallout - Textures.bsa
        ///Fallout - Textures2.bsa
        ///Fallout - Voices1.bsa
        ///FalloutNV.esm
        ///GunRunnersArsenal - Main.bsa
        ///GunRunnersArsenal - Sounds.bsa
        ///GunRunnersArsenal.esm
        ///GUNRUNNERSARSENAL.NAM
        ///HonestHearts [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string falloutNV_base {
            get {
                return ResourceManager.GetString("falloutNV_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon fonv_logo {
            get {
                object obj = ResourceManager.GetObject("fonv_logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
