using System;
using System.Collections.Generic;

namespace Nexus.Client.ModManagement.Scripting
{
	/// <summary>
	/// Identifies the persisted scripted file operation represented by a replay entry.
	/// </summary>
	public enum ScriptedReplayOperationKind
	{
		ArchiveFile,
		GeneratedFile,
		BasicInstall
	}

	/// <summary>
	/// Describes one ordered file operation persisted for deterministic scripted-installer replay.
	/// </summary>
	public sealed class ScriptedReplayOperation
	{
		/// <summary>
		/// Initializes one persisted scripted replay operation.
		/// </summary>
		public ScriptedReplayOperation(ScriptedReplayOperationKind p_srkKind, string p_strSourcePath, string p_strDestinationPath, string p_strPayloadPath, long p_lngPayloadLength, string p_strPayloadHash)
		{
			Kind = p_srkKind;
			SourcePath = p_strSourcePath;
			DestinationPath = p_strDestinationPath;
			PayloadPath = p_strPayloadPath;
			PayloadLength = p_lngPayloadLength;
			PayloadHash = p_strPayloadHash;
		}

		public ScriptedReplayOperationKind Kind { get; private set; }
		public string SourcePath { get; private set; }
		public string DestinationPath { get; private set; }
		public string PayloadPath { get; private set; }
		public long PayloadLength { get; private set; }
		public string PayloadHash { get; private set; }
	}

	/// <summary>
	/// Provides access to the persisted file selections produced by a scripted installer.
	/// </summary>
	public interface IScriptedFileSelectionCache
	{
		/// <summary>
		/// Gets the path of the scripted file-selection cache.
		/// </summary>
		/// <value>The full cache file path.</value>
		string FilePath { get; }

		/// <summary>
		/// Gets whether the scripted file-selection cache currently exists.
		/// </summary>
		/// <value><c>true</c> if the cache exists; otherwise, <c>false</c>.</value>
		bool Exists { get; }

		/// <summary>
		/// Records a source and destination mapping selected by the scripted installer.
		/// </summary>
		/// <param name="p_strFrom">The source path inside the mod archive.</param>
		/// <param name="p_strTo">The destination path selected by the installer.</param>
		void RecordSelection(string p_strFrom, string p_strTo);

		/// <summary>
		/// Records generated bytes so a scripted installation can be replayed without rerunning the installer.
		/// </summary>
		void RecordGeneratedFile(string p_strTo, byte[] p_bteData);

		/// <summary>
		/// Records a scripted request to perform the standard basic installation at this point in the operation order.
		/// </summary>
		void RecordBasicInstall();

		/// <summary>
		/// Loads the ordered source and destination mappings stored in the cache.
		/// </summary>
		/// <returns>The cached mappings, or <c>null</c> when no usable mappings are available.</returns>
		List<KeyValuePair<string, string>> LoadSelections();

		/// <summary>
		/// Loads the complete ordered file replay plan, including generated payloads.
		/// </summary>
		IReadOnlyList<ScriptedReplayOperation> LoadReplayOperations();

		/// <summary>
		/// Gets whether the cache was written by a format that records every replayable file operation.
		/// </summary>
		bool HasCompleteReplay { get; }
	}
}
